//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos_Contables
    {
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int ID_Cliente { get; set; }
        public string Cuenta_contable { get; set; }
        public string Tipo_Movimiento { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
