//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asientos_Contables
    {
        public int ID { get; set; }
        public int ID_Contabilidad { get; set; }
        public string Descripcion { get; set; }
        public int ID_Auxiliar { get; set; }
        public int Codigo_Moneda { get; set; }
        public string Cuenta_CR { get; set; }
        public decimal MontoCR { get; set; }
        public string Cuenta_DB { get; set; }
        public decimal MontoDB { get; set; }
    }
}
