//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturacion
    {
        public int ID { get; set; }
        public int ID_Vendedor { get; set; }
        public int ID_Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Comentario { get; set; }
        public int ID_Articulo { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio_unidad { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Vendedore Vendedore { get; set; }
    }
}
